// <auto-generated />
namespace DCC_Parish_Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FourthMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FourthMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201808192105426_Fourth Mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
